[project]
name = "itw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jay Parmar", email = "jay.parmar@focalworks.in" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
itw = "itw:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
